# docker-compose.yml
version: "3.8"

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravel:/var/www
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - backend

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  n8n:
    image: n8nio/n8n
    container_name: n8n
    volumes:
      - ./n8n:/home/node/.n8n
    env_file:
      - ./n8n/.env
    networks:
      - backend

  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    stdin_open: true
    tty: true
    volumes:
      - ./libretranslate_models:/home/libretranslate/.local/share/argos-translate
    command: >
      --host 0.0.0.0 --port 5000 --debug
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8881:8881"  # Laravel
      - "8882:8882"  # n8n
      - "8883:8883"  # LibreTranslate
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./laravel:/var/www
    depends_on:
      - laravel
      - n8n
      - libretranslate
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge