# docker-compose.yml
version: "3.8"

services:
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./laravel:/var/www
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "${N8N_PORT:-5678}:5678"
    volumes:
      - ./n8n:/home/node/.n8n
    env_file:
      - ./n8n/.env

volumes:
  mysql-data:
