name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  ai_review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch full git history to ensure accurate diffs

      - name: Run CodeRabbit AI PR Reviewer
        uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          REVIEW_MODEL: gpt-4o-mini # Faster and less likely to timeout
          SUMMARY_MODEL: gpt-4o-mini
          EXCLUDE: "**/*.md" # Exclude markdown files; keep JSON for review if needed
          MAX_FILES: 50 # Limit number of files per review to avoid timeouts
          MAX_FILE_SIZE: 100000 # Limit file size (in bytes) to avoid processing very large files
