name: pr-agent

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pr-agent:
    runs-on: ubuntu-latest
    steps:
      - name: PR Agent
        uses: Codium-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: "" # Comment trigger
